services:
  omnichat-backend:
    build: .
    container_name: omnichat-backend
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
    networks:
      - omnichat_net
      - nextcloud_net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - omnichat_net
      - nextcloud_net

volumes:
  ollama_data:

networks:
  omnichat_net:
    driver: bridge
  nextcloud_network:
    external: true # Tells Docker this network already exists (used by Nextcloud)
  nextcloud_net:
    external: true
    name: nextcloud-docker_default